FROM balenalib/%%BALENA_ARCH%%-python

ENV DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket

RUN apt update -y && apt upgrade -y
RUN apt install build-essential pkg-config libdbus-glib-1-dev libgirepository1.0-dev wireless-tools iw vim
RUN python -m pip install wifi dbus-python python-networkmanager

COPY mgr.py mgr.py
COPY btop /bin/btop

CMD tail -f /dev/null