ARG BALENA_ARCH=%%BALENA_ARCH%%
FROM balenalib/$BALENA_ARCH-alpine

ENV DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket

RUN install_packages iw networkmanager

COPY mesh.sh mesh.sh
CMD ./mesh.sh
# CMD tail -f /dev/null